sets.exported={
    main="Carnwenhan",
    sub={ name="Kali", augments={'Mag. Acc.+15','String instrument skill +10','Wind instrument skill +10',}},
    range="Gjallarhorn",
    head="Fili Calot +2",
    body="Fili Hongreline +2",
    hands="Fili Manchettes +2",
    legs="Inyanga Shalwar +2",
    feet="Fili Cothurnes +2",
    neck={ name="Bard's Charm +1", augments={'Path: A',}},
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    right_ear="Etiolation Earring",
    left_ring="Stikini Ring +1",
    right_ring="Defending Ring",
    back={ name="Intarabus's Cape", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
}