sets.exported={
    main={ name="Carnwenhan", augments={'Path: A',}},
    range={ name="Linos", augments={'Accuracy+15','Weapon skill damage +3%','STR+6 VIT+6',}},
    head={ name="Nyame Helm", augments={'Path: B',}},
    body={ name="Nyame Mail", augments={'Path: B',}},
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    legs={ name="Nyame Flanchard", augments={'Path: B',}},
    neck={ name="Warder's Charm +1", augments={'Path: A',}},
    waist="Plat. Mog. Belt",
    left_ear="Regal Earring",
    right_ear={ name="Fili Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+19','Mag. Acc.+19','Damage taken-7%','MND+13 CHR+13',}},
    left_ring="Warp Ring",
    right_ring="Defending Ring",
    back="Moonlight Cape",
}