sets.exported={
    main={ name="Rostam", augments={'Path: A',}},
    sub="Nusku Shield",
    range={ name="Death Penalty", augments={'Path: A',}},
    ammo="Chrono Bullet",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body="Adamantite Armor",
    hands="Regal Gloves",
    legs={ name="Adhemar Kecks +1", augments={'AGI+12','"Rapid Shot"+13','Enmity-6',}},
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck={ name="Comm. Charm +2", augments={'Path: A',}},
    waist="Flume Belt",
    left_ear="Genmei Earring",
    right_ear="Etiolation Earring",
    left_ring="Roller's Ring",
    right_ring="Defending Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}