sets.exported={
    main="Naegling",
    range={ name="Ataktos", augments={'Delay:+60','TP Bonus +1000',}},
    ammo="Chrono Bullet",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body="Adamantite Armor",
    hands={ name="Leyline Gloves", augments={'Accuracy+14','Mag. Acc.+13','"Mag.Atk.Bns."+13','"Fast Cast"+2',}},
    legs="Carmine Cuisses +1",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck={ name="Comm. Charm +2", augments={'Path: A',}},
    waist="Flume Belt",
    left_ear="Genmei Earring",
    right_ear="Etiolation Earring",
    left_ring="Roller's Ring",
    right_ring="Defending Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}