sets.exported={
    main={ name="Carnwenhan", augments={'Path: A',}},
    sub={ name="Ternion Dagger +1", augments={'Path: A',}},
    range="Gjallarhorn",
    head="Mousai Turban +1",
    body="Mou. Manteel +1",
    hands="Mousai Gages +1",
    legs="Mou. Seraweels +1",
    feet="Fili Cothurnes +3",
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    left_ear="Enchntr. Earring +1",
    right_ear={ name="Fili Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+19','Mag. Acc.+19','Damage taken-7%','MND+13 CHR+13',}},
    left_ring="Cornelia's Ring",
    right_ring="Defending Ring",
    back={ name="Intarabus's Cape", augments={'CHR+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Damage taken-5%',}},
}