sets.exported={
    main={ name="Tizona", augments={'Path: A',}},
    sub={ name="Thibron", augments={'TP Bonus +1000',}},
    ammo="Staunch Tathlum +1",
    head="Malignance Chapeau",
    body="Hashishin Mintan +3",
    hands={ name="Leyline Gloves", augments={'Accuracy+14','Mag. Acc.+13','"Mag.Atk.Bns."+13','"Fast Cast"+2',}},
    legs="Hashishin Tayt +3",
    feet="Hashi. Basmak +3",
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Carrier's Sash",
    left_ear="Etiolation Earring",
    right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    right_ring="Stikini Ring +1",
    back={ name="Rosmerta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Spell interruption rate down-10%',}},
}